spring.application.name=carportal

spring.datasource.url=jdbc:mysql://localhost:3306/carportaldb
spring.datasource.username=root
spring.datasource.password=test

spring.jpa.hibernate.ddl-auto=update

jwt.key = zxcvb-zxcvb-zxcvb-hgfdfhh
jwt.expiry-time= 864000
jwt.issuer =carportal.com